name: Build .NET Project

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 * * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '7.0.x'

      - name: Restore dependencies
        run: |
          for project in $(find . -name "*.csproj"); do
            dotnet restore "$project"
          done

      - name: Build all projects
        run: |
          for project in $(find . -name "*.csproj"); do
            dotnet build "$project" --no-restore
          done
